### ISSUE TITLE
Cannot find module 'vpk'

### ISSUE THREAD

**Issue by checklx** [Step7750/node-csgo-cdn#27]
I am having Cannot find module 'vpk' error.
I also don't know how to set up to work. Can anyone help me?

**Comment by iDefineHD** [comment]
This is very generic, did you npm install?

**Comment by checklx** [comment]
@iDefineHD 
I installed it. 

- C:\Users\1\Desktop\node-csgo-cdn-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\1\Desktop\node-csgo-cdn-master\index.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\1\\Desktop\\node-csgo-cdn-master\\index.js' ]
}
This is the information I received.

**Comment by Step7750** [comment]
This is likely user error. You'll want to `npm install` this (add as a dependency to your package.json).
